// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6hQtaeIWtxnkNKFZtiOZm2gX7JkU9M4',
    appId: '1:434854421240:web:cd56866a96a739dc18110d',
    messagingSenderId: '434854421240',
    projectId: 'polling-6aa12',
    authDomain: 'polling-6aa12.firebaseapp.com',
    storageBucket: 'polling-6aa12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4FGoXmLjcROzjwkL1jJa12IoX3mb9QY',
    appId: '1:434854421240:android:1c37b01b5f0c165a18110d',
    messagingSenderId: '434854421240',
    projectId: 'polling-6aa12',
    storageBucket: 'polling-6aa12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVB9jCpqjMJ5fG0OXEudEcnFYsdJ2LEU',
    appId: '1:434854421240:ios:c6f89dd6630ae8bb18110d',
    messagingSenderId: '434854421240',
    projectId: 'polling-6aa12',
    storageBucket: 'polling-6aa12.appspot.com',
    iosBundleId: 'com.example.pollapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVB9jCpqjMJ5fG0OXEudEcnFYsdJ2LEU',
    appId: '1:434854421240:ios:c6f89dd6630ae8bb18110d',
    messagingSenderId: '434854421240',
    projectId: 'polling-6aa12',
    storageBucket: 'polling-6aa12.appspot.com',
    iosBundleId: 'com.example.pollapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn6hQtaeIWtxnkNKFZtiOZm2gX7JkU9M4',
    appId: '1:434854421240:web:991f2c20ca22e3f718110d',
    messagingSenderId: '434854421240',
    projectId: 'polling-6aa12',
    authDomain: 'polling-6aa12.firebaseapp.com',
    storageBucket: 'polling-6aa12.appspot.com',
  );
}
